- hosts: all
  sudo: True
  vars:
    graphite:
      version: master
      timezone: America/New_York
      workers: 4
      host: 0.0.0.0
      server: graphite.local
      secret_key: 'statsd_j^!rt)5f-3l*wb#-jt+-$#p99^cf$5y4^k1)k@hopsjuvj%7'
    carbon:
      host: 0.0.0.0
      ssl: no
    db_graphite:
      name: graphite
      user: graphite
      password: graphite
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none
    - postgres
    - graphite
    - nodejs
    - statsd

